StatCan/tass-ssat

.gitignore

Create .gitignore from github template.

---

environment.yaml

Feature conda enviro 6

---

doc/ReleaseProcess.md

Created first draft of ReleaseProcess.md file.

---

doc/BestPractices.md

Doc best practices 13

---

templates/templates.json
tests/test_jsonschema.py

Feature configfiles 2

---

tass/actions/actions.py

A quick fix for flake8 violations.

Clean up. Fixed the flagged Flake8 issues.

---

README.md

Doc 39 readme update

---

demo/tass_sample.json
tass/__main__.py
tass/actions/selenium.py
tass/core/tass_case.py
tass/exceptions/assertion_errors.py
tests/actions/test_selenium.py
tests/pages/page1.html

Initial implementation of assertions within the framework. Also includes the groundwork for test tracking for  the future implementation of a reporting tool.

Feature Added - Selenium assertion: is Displayed

---

demo/tass_sample.json
tass/__main__.py
tass/actions/selenium.py
tass/core/tass_case.py
tass/core/tass_files.py
tass/drivers/browserdriver.py
tass/exceptions/assertion_errors.py
tests/actions/test_selenium.py
tests/pages/page1.html

Added report generation following a completed run using simple json format.

Feature 44 produce a report from the test results

---

demo/tass_sample.json
tass/actions/selenium.py
tests/actions/test_selenium.py

Refactored type function to eliminate conflict with builtin function

Bugfix. Refactored type function

---

README.md
conda-recipe/meta.yaml
environment.yaml

Created conda packaging script and provided some updates to the README.

Created conda package and updated readme.

---

src/tass/actions/selenium.py
tests/actions/test_selenium.py
tests/pages/page1.html

Feature 55 selectdropdown

---

demo/tass_sample.json
pages/sample.json
src/tass/actions/actions.py
src/tass/actions/selenium.py
src/tass/actions/selenium_wait.py
src/tass/drivers/browserdriver.py
tests/actions/test_selenium_wait.py
tests/pages/page1.html

Added explicit waits. Updated existing implementations to account for changes. Unit tests to be added.

Feature 17 explicit wait wait until

---

conda-recipe/meta.yaml
pyproject.toml

Updated project files for version 0.3.0.

---

environment.yaml
src/tass/actions/selenium.py
src/tass/actions/selenium_wait.py
src/tass/config/browsers.json
src/tass/drivers/browserdriver.py
tests/actions/test_selenium.py
tests/actions/test_selenium_wait.py

Changes:
- Removed dependency on webdriver-manager in favour of selenium-manager (bundled with Selenium).
- Added option to add parameters to locators at runtime using the "Step" argument: locator_args.
- Re-formatted browser configuration to include arguments (flags) and preferences (key/value pairs).
- Added unit tests for dynamic locators

Feature 81 update selenium actions to allow for parameterized locators

---

src/tass/__main__.py
src/tass/core/page_reader.py
tests/actions/test_selenium.py
tests/test_pagereader.py

Small Bugfixes

---

src/tass/core/page_reader.py
tests/test_pagereader.py

Feature 92 implement page pom inheritance

---

README.md
conda-recipe/meta.yaml
pyproject.toml

Prepped for 0.5.0 pre-release.

V0.5.0 pre release

---

tass-converter/src/tass/converter/conf.py
tass-converter/src/tass/converter/page_conf.py

closes #129 
- Conversion now ignores empty rows (any row that does not have a value for Column A [uuid])
- Conversion template now includes a terminating header "//end//" all columns to the right of this header will be ignored.

[Feature][tass-converter] Updated Excel Scenario converter behaviour

---

tass-base/conda-recipe/meta.yaml
tass-base/pyproject.toml
tass-converter/conda-recipe/meta.yaml
tass-converter/pyproject.toml

Updated version number in preparation for new release.

Prepared for release v0.6.1

---

tass-base/src/tass/base/actions/selenium.py

Fixed issue with using a single string for locator_args

Fixed locator args to handle non-list entries

---

README.md
scripting/install_tass.cmd
scripting/install_tass.sh

- Created CMD install script.
- Created zsh install script (should work on other shells if first line is edited).
- Updated README with install script information.
Closes #113.

Feature 113 install script

---

.gitignore
tass-base/src/tass/base/__main__.py
tass-base/src/tass/base/core/page_reader.py
tass-base/src/tass/base/core/secrets.py

- Added try except statements to with open statements in tass base __main__.py file.
- Added try except statements to with open statements in tass base core page_reader.py file.
- Added try except statements to with open statements in tass secrets.py file.
- Updated .gitignore with folders created by running tass.
Closes #144.

Feature 144 log update

---

tass-base/conda-recipe/meta.yaml
tass-base/pyproject.toml

Updated dependencies. Updated version for release.

---

tass-base/src/tass/base/actions/core.py
tass-base/src/tass/base/schema/parser.py
tass-base/tests/actions/test_core.py

176 feature add delay function to core functions

---

tass-base/src/tass/base/actions/selenium.py
tass-base/tests/actions/test_selenium.py
tass-base/tests/pages/page1.html

179 feature assert field attribute displayed

---

tass-base/conda-recipe/meta.yaml
tass-base/pyproject.toml
tass-converter/conda-recipe/meta.yaml
tass-converter/pyproject.toml
tass-orchestrator/conda-recipe/meta.yaml
tass-orchestrator/pyproject.toml
tass-report/conda-recipe/meta.yaml
tass-report/pyproject.toml

[RELEASE CANDIDATE] v0.9.0 release candidate

---

tass-core/src/tass/core/actions/selenium.py

Added cast to string for html attribute in selenium actions.

186 refactor update converter to convert all html attribute values to strings from the excel

---

README.md
tass-converter/README.md
tass-core/README.md
tass-orchestrator/README.md

Updated README files for v.0.9.0

---

tass-core/src/tass/core/actions/selenium.py
tass-core/src/tass/core/actions/selenium_action_manager.py
tass-core/src/tass/core/drivers/driverconfig.py
tass-core/tests/actions/test_selenium.py

Closes #190
Added easy access browser name, version and platform properties.

Added screenshot function and tests.

---

tass-core/src/tass/core/actions/core_action_manager.py
tass-core/src/tass/core/actions/selenium.py
tass-core/src/tass/core/actions/selenium_action_manager.py
tass-core/src/tass/core/actions/selenium_chain.py
tass-core/src/tass/core/drivers/driverconfig.py
tass-core/src/tass/core/schema/parser.py
tass-core/tests/actions/test_core.py
tass-core/tests/actions/test_selenium_chain.py
tass-core/tests/pages/page1.html

Added selenium action chain implementation, allowing more advanced users to chain together multiple discrete actions to create custom combinations of inputs. Full support for Selenium ActionChains is ongoing and currently incomplete.
Closes #191

Selenium Action Chain Implementation

---

tass-core/src/tass/core/actions/selenium.py
tass-core/tests/actions/test_selenium.py

Function will now log the closed window error, and attempt to continue the command.

Fixed switch_window bug.

---

tass-core/src/tass/core/drivers/custombrowserdrivers.py
tass-core/src/tass/core/drivers/driverconfig.py
tass-core/tests/actions/test_selenium.py
tass-core/tests/actions/test_selenium_chain.py
tass-core/tests/actions/test_selenium_wait.py

- Added support for Safari Driver
- closes #216 
- closes #221 
- Updated Unit tests for clarity and reliability.

216 add safari support
